1️⃣ Processing Pipelines

Description:
These are data-intensive (and sometimes compute-intensive) applications organized as a sequence of stages. Each stage processes the output of the previous one.

Examples (from PDF context):

Indexing for large datasets generated by web crawlers

Document processing pipelines (e.g., conversion, encryption, OCR)

Video transcoding pipelines (converting videos to multiple formats)

Why cloud fits:

Each stage can scale independently

Parallelism reduces total processing time
